urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

app_name = "django_survey"

urlpatterns = [
    url(r"^(?P<token>[0-9a-zA-Z]{50})/answer/$", views.answer, name="answer"),
    url(r"^(?P<token>[0-9a-zA-Z]{50})/process_answer/$",
        views.process_answer, name="process_answer"),
    url(r"^(?P<token>[0-9a-zA-Z]{50})/finish/$",
        views.close_survey, name="close_survey"),
    ]

models.py
# -*- coding: utf-8 -*-
import random
import string
from datetime import datetime

from django.db import models
from django.template.defaultfilters import date as _date
from django.core.urlresolvers import reverse

from .google_mail import send_email

SCORE_MAX = 4

class MailConfig(models.Model):

    name = models.CharField("Nom", max_length=50)
    domain = models.CharField("Domaine", max_length=50)
    sender = models.EmailField("Expéditeur")
    password = models.CharField("Mot de passe", max_length=20)
    subject = models.CharField("Objet", max_length=100, default="#SUBJECT#")
    message = models.TextField(
        "Message",
        blank=True,
        default="Bonjour #TITLE# #FIRSTNAME# #LASTNAME#\r\n"
        	"Concernant l'évènement du #DATE#,\r\n"
        	"Pourriez-vous répondre à l'enquête accessible "
        	"via le lien ci-dessous ?\r\n\r\n"
        	"#LINK#",
        help_text="Message à envoyer pour l'invitation à participer "
        "à l'enquête. Les tags disponibles sont : "
        "#SUBJECT#, #DATE#, #TITLE#, #FIRSTNAME#, #LASTNAME#, "
        "#LINK#")

    class Meta:
        verbose_name = "Configuration de messagerie"
        verbose_name_plural = "Configurations de messagerie"

    def __str__(self):
        return self.name


class Questionnaire(models.Model):

    title = models.CharField("Titre", max_length=200)
    mail_config = models.ForeignKey(
        MailConfig,
        verbose_name="Configuration de la messagerie"
        )

    class Meta:
        verbose_name = "questionnaire"
        verbose_name_plural = "questionnaires"

    def __str__(self):
        return self.title


class Question(models.Model):

    question_text = models.CharField("Question", max_length=200)
    record = models.BooleanField("Question récapitulative ?", default=False)
    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "question"
        verbose_name_plural = "questions"

    def __str__(self):
        return self.question_text


class Survey(models.Model):

    TITLE_CHOICES = (
            ("Monsieur", "Monsieur"),
            ("Madame", "Madame"),
            ("Mademoiselle", "Mademoiselle")
        )
    token = models.SlugField(max_length=50, blank=True)
    subject = models.CharField("Objet de l'enquête", max_length=100)
    title = models.CharField(
        max_length=12,
        choices=TITLE_CHOICES,
        default="Monsieur",
        blank=True)
    firstname = models.CharField(
        "Prénom", max_length=50, blank=True)
    lastname = models.CharField("nom", max_length=50, blank=True)
    email = models.EmailField("Adresse mail")
    event_date = models.DateField("Date évènement", null=True, blank=True)
    date_sent = models.DateField("Date d'envoi", null=True, blank=True)
    date_received = models.DateField(
        "Date de réception", null=True, blank=True)
    sent = models.BooleanField("Envoyé", default=False)
    questionnaire = models.ForeignKey(Questionnaire)
    current_questionnaire = models.IntegerField(null=True, blank=True)
    remarks = models.TextField("Remarques", blank=True)
    suggestions = models.TextField("Suggestions", blank=True)

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = ''.join(
                random.sample(string.ascii_letters + string.digits, 50))
        if not self.sent:
            html_subject = self.prepare_message(
                self.questionnaire.mail_config.subject)
            html_message = self.prepare_message(
                self.questionnaire.mail_config.message)
            send_email(
                self.questionnaire.mail_config.sender,
                self.questionnaire.mail_config.password,
                self.email,
                html_subject,
                html_message)
            self.date_sent = datetime.today()
            self.sent = True
        super().save(*args, **kwargs)

        if (self.current_questionnaire and
                (self.questionnaire.id != self.current_questionnaire)):
            self.surveyquestion_set.all().delete()
        self.current_questionnaire = self.questionnaire.id
        super().save(*args, **kwargs)
        if not self.surveyquestion_set.all().count():
            for question in self.questionnaire.question_set.all():
                self.surveyquestion_set.create(
                    question_text=question.question_text,
                    record=question.record)

    def completed(self):
        return len(self.surveyquestion_set.filter(score__isnull=True)) == 0
    completed.boolean = True
    completed.short_description = 'Complétée'

    def score_max(self):
        return len(self.surveyquestion_set.all()) * SCORE_MAX
    score_max.short_description = "Score maximum"

    def score(self):
        if self.completed():
            return self.surveyquestion_set.all().aggregate(
                models.Sum("score"))["score__sum"]
        else:
            return None

    class Meta:
        verbose_name = "Enquête"
        verbose_name_plural = "Enquêtes"

    def __str__(self):
        return ", ".join([self.subject, self.email])

    def prepare_message(self, message):
        html_message = message.replace("\r\n", "<br />")
        survey_link = "".join(
                [
                    self.questionnaire.mail_config.domain,
                    reverse("django_survey:answer", args=(self.token,))
                ]
            )
        html_message = html_message.replace(
            "#LINK#",
            '<a href="%s">lien vers l\'enquête</a>' % survey_link)
        html_message = html_message.replace(
            "#SUBJECT#",
            self.subject)
        html_message = html_message.replace(
            "#DATE#",
            _date(self.event_date, "d F Y"))
        html_message = html_message.replace(
            "#TITLE#",
            self.title)
        html_message = html_message.replace(
            "#FIRSTNAME#",
            self.firstname)
        html_message = html_message.replace(
            "#LASTNAME#",
            self.lastname)
        return html_message


class SurveyQuestion(models.Model):

    question_text = models.CharField("Question", max_length=200)
    record = models.BooleanField("Question récapitulative ?", default=False)
    score = models.IntegerField(null=True, blank=True)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "question"
        verbose_name_plural = "questions"

    def __str__(self):
        return ""

views.py
# -*- coding: utf-8 -*-
from datetime import datetime
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Survey


def answer(request, token, error=False):
    survey = get_object_or_404(Survey, token=token)
    if survey.completed():
        return HttpResponseRedirect(
            reverse("django_survey:close_survey", args=(token,)))
    else:
        if error:
            error_message = "Veuillez répondre aux questions "
            "suivantes pour compléter l'enquête"
        else:
            error_message = None
        return render(
            request, "django_survey/answer.html",
            context={"survey": survey, "error_message": error_message})


def process_answer(request, token):
    survey = get_object_or_404(Survey, token=token)
    if survey.completed():
        return HttpResponseRedirect(
            reverse("django_survey:close_survey", args=(token,)))

    for q in survey.surveyquestion_set.filter(score__isnull=True):
        try:
            score = request.POST[str(q.id)]
            q.score = score
            q.save()
        except KeyError:
            pass
    survey.remarks = request.POST["remarks"]
    survey.suggestions = request.POST["suggestions"]
    survey.save()

    not_answered_questions = survey.surveyquestion_set.filter(
        score__isnull=True).count()
    if not_answered_questions > 0:
        return answer(request, token, error=True)
    survey.date_received = datetime.today()
    survey.save()
    return HttpResponseRedirect(
        reverse("django_survey:close_survey", args=(token,)))


def close_survey(request, token):
    survey = get_object_or_404(Survey, token=token)
    return render(
        request, "django_survey/finish.html",
        context={"survey": survey}
        )

templates/django_survey/answer.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>{{ survey.subject }}</title>
    </head>
    <body>
        <h2>Réponse à l'enquête - {{ survey.subject  }}</h2>
        
        {% if error_message %}
            <p style="color:red;"><em>{{ error_message}}</em></p>
        {% endif %}
        
        <form action="{% url 'django_survey:process_answer' survey.token %}" method="post" />
            {% csrf_token %}
        
            <table border="1px">
                    <tr>
                        <th align="center">Question</th>
                        <th align="center" width="50px"><img src="{% static "img/very_angry.png" %}" alt="very_angry" width="30px"/></th>
                        <th align="center" width="50px"><img src="{% static "img/angry.png" %}" alt="angry" width="30px"/></th>
                        <th align="center" width="50px"><img src="{% static "img/neutral.png" %}" alt="neutral" width="30px"/></th>
                        <th align="center" width="50px"><img src="{% static "img/happy.png" %}" alt="happy" width="30px"/></th>
                        <th align="center" width="50px"><img src="{% static "img/very_happy.png" %}" alt="very_happy" width="30px"/></th>
                    </tr>
                {% for line in survey.surveyquestion_set.all %}
                    {% if not line.score %}
                    <tr height="30px">
                        <td>{% if line.record %}<b>{% endif %} {{ line.question_text }} {% if line.record %}</b>{% endif %}</td>
                        <td align="center"><input type="radio" name="{{ line.id }}" value=0 /></td>
                        <td align="center"><input type="radio" name="{{ line.id }}" value=1 /></td>
                        <td align="center"><input type="radio" name="{{ line.id }}" value=2 /></td>
                        <td align="center"><input type="radio" name="{{ line.id }}" value=3 /></td>
                        <td align="center"><input type="radio" name="{{ line.id }}" value=4 /></td>
                    </tr>
                    {% endif %}
                {% endfor %}
            </table>

            <h4>Remarques <em>(facultatif) :</em><br/>
                <textarea id="remark" name="remarks" rows="10" cols="50">{{ survey.remarks }}</textarea>
            </h4>
            
            <h4>Suggestions <em>(facultatif) :</em><br/>
                <textarea name="suggestions" rows="10" cols="50">{{ survey.suggestions }}</textarea>
            </h4>
            
            <input type="submit" value="Valider" />
        </form>
     </body>
</html> 

templates/django_survey/finish.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Clôture</title>
</head>
<body>
    <img src="{% static 'img/thumb_up.png'%}" alt="Merci"/>
    <h2>L'enquête {{survey.subject}} est maintenant terminée</h2>
    <h3>Merci d'avoir participé à l'amélioration de nos services</h3>
</body>
</html>